config/routes.rb
OurApp::Application.routes.draw do
  resources :sus

  resources :feedbacks

  resources :schedules

  get "admin/index"

  controller :sessions do
  	get 'login' => :new
  	post 'login' => :create
  	delete 'logout' => :destroy
  end

  resources :profiles

  resources :users

  resources :meal_meetings

end

app/models/sus.rb
class Sus < ActiveRecord::Base
  attr_accessible :q1, :q10, :q2, :q3, :q4, :q4, :q5, :q6, :q7, :q8, :q9, :score
end

app/controllers/sus_controller.rb
class SusController < ApplicationController
  # GET /sus
  # GET /sus.json
  def index
    @sus = Sus.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @sus }
    end
  end

  # GET /sus/1
  # GET /sus/1.json
  def show
    @su = Sus.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @su }
    end
  end

  # GET /sus/new
  # GET /sus/new.json
  def new
    @su = Sus.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @su }
    end
  end

  # GET /sus/1/edit
  def edit
    @su = Sus.find(params[:id])
  end

  # POST /sus
  # POST /sus.json
  def create
    @su = Sus.new(params[:su])

    respond_to do |format|
      if @su.save
        format.html { redirect_to @su, notice: 'Sus was successfully created.' }
        format.json { render json: @su, status: :created, location: @su }
      else
        format.html { render action: "new" }
        format.json { render json: @su.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /sus/1
  # PUT /sus/1.json
  def update
    @su = Sus.find(params[:id])

    respond_to do |format|
      if @su.update_attributes(params[:su])
        format.html { redirect_to @su, notice: 'Sus was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @su.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sus/1
  # DELETE /sus/1.json
  def destroy
    @su = Sus.find(params[:id])
    @su.destroy

    respond_to do |format|
      format.html { redirect_to sus_index_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/s_us_helper.rb
module SUsHelper
end

app/views/sus/_form.html.erb
<%= form_for(@su) do |f| %>
  <% if @su.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@su.errors.count, "error") %> prohibited this su from being saved:</h2>

      <ul>
      <% @su.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="radio_field">
    <%= f.radio_button :q1, "1" %>
    <%= f.label(:q1, raw("Strongly Disagree<br>1")) %>
    <%= f.radio_button :q1, "2" %>
    <%= f.label(:q1, raw("<br>2")) %>
    <%= f.radio_button :q1, "3" %>
    <%= f.label(:q1, raw("<br>3")) %>
    <%= f.radio_button :q1, "4" %>
    <%= f.label(:q1, raw("<br>4")) %>
    <%= f.radio_button :q1, "5" %>
    <%= f.label(:q1, raw("Strongly Agree<br>5")) %>
  </div>
  <div class="radio_field">
    <%= f.radio_button :q2, "1" %>
    <%= f.label(:q2, raw("Strongly Disagree<br>1")) %>
    <%= f.radio_button :q2, "2" %>
    <%= f.label(:q2, raw("<br>2")) %>
    <%= f.radio_button :q2, "3" %>
    <%= f.label(:q2, raw("<br>3")) %>
    <%= f.radio_button :q2, "4" %>
    <%= f.label(:q2, raw("<br>4")) %>
    <%= f.radio_button :q2, "5" %>
    <%= f.label(:q2, raw("Strongly Agree<br>5")) %>
  </div>
  <div class="radio_field">
    <%= f.radio_button :q3, "1" %>
    <%= f.label(:q3, raw("Strongly Disagree<br>1")) %>
    <%= f.radio_button :q3, "2" %>
    <%= f.label(:q3, raw("<br>2")) %>
    <%= f.radio_button :q3, "3" %>
    <%= f.label(:q3, raw("<br>3")) %>
    <%= f.radio_button :q3, "4" %>
    <%= f.label(:q3, raw("<br>4")) %>
    <%= f.radio_button :q3, "5" %>
    <%= f.label(:q3, raw("Strongly Agree<br>5")) %>
  </div>
  <div class="radio_field">
    <%= f.radio_button :q4, "1" %>
    <%= f.label(:q4, raw("Strongly Disagree<br>1")) %>
    <%= f.radio_button :q4, "2" %>
    <%= f.label(:q4, raw("<br>2")) %>
    <%= f.radio_button :q4, "3" %>
    <%= f.label(:q4, raw("<br>3")) %>
    <%= f.radio_button :q4, "4" %>
    <%= f.label(:q4, raw("<br>4")) %>
    <%= f.radio_button :q4, "5" %>
    <%= f.label(:q4, raw("Strongly Agree<br>5")) %>
  </div>
  <div class="radio_field">
    <%= f.radio_button :q5, "1" %>
    <%= f.label(:q5, raw("Strongly Disagree<br>1")) %>
    <%= f.radio_button :q5, "2" %>
    <%= f.label(:q5, raw("<br>2")) %>
    <%= f.radio_button :q5, "3" %>
    <%= f.label(:q5, raw("<br>3")) %>
    <%= f.radio_button :q5, "4" %>
    <%= f.label(:q5, raw("<br>4")) %>
    <%= f.radio_button :q5, "5" %>
    <%= f.label(:q5, raw("Strongly Agree<br>5")) %>
  </div>
  <div class="radio_field">
    <%= f.radio_button :q6, "1" %>
    <%= f.label(:q6, raw("Strongly Disagree<br>1")) %>
    <%= f.radio_button :q6, "2" %>
    <%= f.label(:q6, raw("<br>2")) %>
    <%= f.radio_button :q6, "3" %>
    <%= f.label(:q6, raw("<br>3")) %>
    <%= f.radio_button :q6, "4" %>
    <%= f.label(:q6, raw("<br>4")) %>
    <%= f.radio_button :q6, "5" %>
    <%= f.label(:q6, raw("Strongly Agree<br>5")) %>
  </div>
  <div class="radio_field">
    <%= f.radio_button :q7, "1" %>
    <%= f.label(:q7, raw("Strongly Disagree<br>1")) %>
    <%= f.radio_button :q7, "2" %>
    <%= f.label(:q7, raw("<br>2")) %>
    <%= f.radio_button :q7, "3" %>
    <%= f.label(:q7, raw("<br>3")) %>
    <%= f.radio_button :q7, "4" %>
    <%= f.label(:q7, raw("<br>4")) %>
    <%= f.radio_button :q7, "5" %>
    <%= f.label(:q7, raw("Strongly Agree<br>5")) %>
  </div>
  <div class="radio_field">
    <%= f.radio_button :q8, "1" %>
    <%= f.label(:q8, raw("Strongly Disagree<br>1")) %>
    <%= f.radio_button :q8, "2" %>
    <%= f.label(:q8, raw("<br>2")) %>
    <%= f.radio_button :q8, "3" %>
    <%= f.label(:q8, raw("<br>3")) %>
    <%= f.radio_button :q8, "4" %>
    <%= f.label(:q8, raw("<br>4")) %>
    <%= f.radio_button :q8, "5" %>
    <%= f.label(:q8, raw("Strongly Agree<br>5")) %>
  </div>
  <div class="radio_field">
    <%= f.radio_button :q9, "1" %>
    <%= f.label(:q9, raw("Strongly Disagree<br>1")) %>
    <%= f.radio_button :q9, "2" %>
    <%= f.label(:q9, raw("<br>2")) %>
    <%= f.radio_button :q9, "3" %>
    <%= f.label(:q9, raw("<br>3")) %>
    <%= f.radio_button :q9, "4" %>
    <%= f.label(:q9, raw("<br>4")) %>
    <%= f.radio_button :q9, "5" %>
    <%= f.label(:q9, raw("Strongly Agree<br>5")) %>
  </div>
  <div class="radio_field">
    <%= f.radio_button :q10, "1" %>
    <%= f.label(:q10, raw("Strongly Disagree<br>1")) %>
    <%= f.radio_button :q10, "2" %>
    <%= f.label(:q10, raw("<br>2")) %>
    <%= f.radio_button :q10, "3" %>
    <%= f.label(:q10, raw("<br>3")) %>
    <%= f.radio_button :q10, "4" %>
    <%= f.label(:q10, raw("<br>4")) %>
    <%= f.radio_button :q10, "5" %>
    <%= f.label(:q10, raw("Strongly Agree<br>5")) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
  <script>
  	$(.radio_field).buttonset();
<% end %>

app/views/sus/edit.html.erb
<h1>Editing su</h1>

<%= render 'form' %>

<%= link_to 'Show', @su %> |
<%= link_to 'Back', sus_index_path %>

app/views/sus/index.html.erb
<h1>Listing sus</h1>

<table>
  <tr>
    <th>Q1</th>
    <th>Q2</th>
    <th>Q3</th>
    <th>Q4</th>
    <th>Q4</th>
    <th>Q5</th>
    <th>Q6</th>
    <th>Q7</th>
    <th>Q8</th>
    <th>Q9</th>
    <th>Q10</th>
    <th>Score</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @sus.each do |su| %>
  <tr>
    <td><%= su.q1 %></td>
    <td><%= su.q2 %></td>
    <td><%= su.q3 %></td>
    <td><%= su.q4 %></td>
    <td><%= su.q4 %></td>
    <td><%= su.q5 %></td>
    <td><%= su.q6 %></td>
    <td><%= su.q7 %></td>
    <td><%= su.q8 %></td>
    <td><%= su.q9 %></td>
    <td><%= su.q10 %></td>
    <td><%= su.score %></td>
    <td><%= link_to 'Show', su %></td>
    <td><%= link_to 'Edit', edit_su_path(su) %></td>
    <td><%= link_to 'Destroy', su, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Sus', new_su_path %>

app/views/sus/new.html.erb
<h2>How well does our site work?</h2>

<%= render 'form' %>

<%= link_to 'Back', sus_index_path %>

app/views/sus/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Q1:</b>
  <%= @su.q1 %>
</p>

<p>
  <b>Q2:</b>
  <%= @su.q2 %>
</p>

<p>
  <b>Q3:</b>
  <%= @su.q3 %>
</p>

<p>
  <b>Q4:</b>
  <%= @su.q4 %>
</p>

<p>
  <b>Q4:</b>
  <%= @su.q4 %>
</p>

<p>
  <b>Q5:</b>
  <%= @su.q5 %>
</p>

<p>
  <b>Q6:</b>
  <%= @su.q6 %>
</p>

<p>
  <b>Q7:</b>
  <%= @su.q7 %>
</p>

<p>
  <b>Q8:</b>
  <%= @su.q8 %>
</p>

<p>
  <b>Q9:</b>
  <%= @su.q9 %>
</p>

<p>
  <b>Q10:</b>
  <%= @su.q10 %>
</p>

<p>
  <b>Score:</b>
  <%= @su.score %>
</p>


<%= link_to 'Edit', edit_su_path(@su) %> |
<%= link_to 'Back', sus_index_path %>