config/routes.rb
OurApp::Application.routes.draw do
  resources :sus

  resources :feedbacks

  resources :schedules

  get "admin/index"

  controller :sessions do
  	get 'login' => :new
  	post 'login' => :create
  	delete 'logout' => :destroy
  end

  resources :profiles

  resources :users

  resources :meal_meetings

end

app/models/meal_meeting.rb
class MealMeeting < ActiveRecord::Base
  attr_accessible :interests, :location, :time, :title
end

app/controllers/meal_meetings_controller.rb
class MealMeetingsController < ApplicationController
  # GET /meal_meetings
  # GET /meal_meetings.json
  def index
    @meal_meetings = MealMeeting.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @meal_meetings }
    end
  end

  # GET /meal_meetings/1
  # GET /meal_meetings/1.json
  def show
    @meal_meeting = MealMeeting.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @meal_meeting }
    end
  end

  # GET /meal_meetings/new
  # GET /meal_meetings/new.json
  def new
    @meal_meeting = MealMeeting.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @meal_meeting }
    end
  end

  # GET /meal_meetings/1/edit
  def edit
    @meal_meeting = MealMeeting.find(params[:id])
  end

  # POST /meal_meetings
  # POST /meal_meetings.json
  def create
    @meal_meeting = MealMeeting.new(params[:meal_meeting])

    respond_to do |format|
      if @meal_meeting.save
        format.html { redirect_to @meal_meeting, notice: 'Meal meeting was successfully created.' }
        format.json { render json: @meal_meeting, status: :created, location: @meal_meeting }
      else
        format.html { render action: "new" }
        format.json { render json: @meal_meeting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /meal_meetings/1
  # PUT /meal_meetings/1.json
  def update
    @meal_meeting = MealMeeting.find(params[:id])

    respond_to do |format|
      if @meal_meeting.update_attributes(params[:meal_meeting])
        format.html { redirect_to @meal_meeting, notice: 'Meal meeting was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @meal_meeting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /meal_meetings/1
  # DELETE /meal_meetings/1.json
  def destroy
    @meal_meeting = MealMeeting.find(params[:id])
    @meal_meeting.destroy

    respond_to do |format|
      format.html { redirect_to meal_meetings_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/meal_meetings_helper.rb
module MealMeetingsHelper
end

app/views/meal_meetings/_form.html.erb
<%= form_for(@meal_meeting) do |f| %>
  <% if @meal_meeting.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@meal_meeting.errors.count, "error") %> prohibited this meal_meeting from being saved:</h2>

      <ul>
      <% @meal_meeting.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :interests %><br />
    <%= f.text_area :interests, :rows => 6 %>
  </div>
  <div class="field">
    <%= f.label :time %><br />
    <%= f.text_field :time %>
  </div>
  <div class="field">
    <%= f.label :location %><br />
    <%= f.text_field :location %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/meal_meetings/edit.html.erb
<h1>Editing meal_meeting</h1>

<%= render 'form' %>

<%= link_to 'Show', @meal_meeting %> |
<%= link_to 'Back', meal_meetings_path %>

app/views/meal_meetings/new.html.erb
<h1>Entertain!</h1>

<%= render 'form' %>

<%= link_to 'Back', meal_meetings_path %>

<script>
	$(function() {
	  var availableInterests = [
	    "Japanese",
	    "Baseball",
	    "Politics",
	    "Comic books",
	    "Independent Films"
	    ];
	
	  $("#meal_meeting_time" ).datepicker();
	  $("#meal_meeting_interests" )
	    .bind("keydown", function(event) {
	      if (event.keyCode === $.ui.keyCode.TAB &&
	      	  $( this).data("autocomplete").menu.active ) {
	      	event.preventDefault();
	      }
	    })
	    .autocomplete({
	      minLength: 2,
	      source: function(request, response) {
	        response($.ui.autocomplete.filter(availableInterests, extractLast(request.term)));
	      },
	      focus: function() {return false;},
	      select: function(event, ui) {
	        var terms = split(this.value);
	        terms.pop();
	        terms.push(ui.item.value);
	        terms.push("");
	        this.value = terms.join(", ");
	        return false;
	        }
	    });
	  
	  function split( val) {
	    return val.split(/,\s*/);
	  }
	  function extractLast(term) {
	    return split(term).pop();
	  }
	});
</script>

app/views/meal_meetings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @meal_meeting.title %>
</p>

<p>
  <b>Interests:</b>
  <%= @meal_meeting.interests %>
</p>

<p>
  <b>Time:</b>
  <%= @meal_meeting.time %>
</p>

<p>
  <b>Location:</b>
  <%= @meal_meeting.location %>
</p>


<%= link_to 'Edit', edit_meal_meeting_path(@meal_meeting) %> |
<%= link_to 'Back', meal_meetings_path %>