config/routes.rb
OurApp::Application.routes.draw do
  resources :sus

  resources :feedbacks

  resources :schedules

  get "admin/index"

  controller :sessions do
  	get 'login' => :new
  	post 'login' => :create
  	delete 'logout' => :destroy
  end

  resources :profiles

  resources :users

  resources :meal_meetings

end

app/models/feedback.rb
class Feedback < ActiveRecord::Base
  attr_accessible :content, :email
  validates :email, :presence => true
  validates :content, :presence => true
end

app/controllers/feedbacks_controller.rb
class FeedbacksController < ApplicationController
	skip_before_filter :authorize
  # GET /feedbacks
  # GET /feedbacks.json
  def index
    @feedbacks = Feedback.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @feedbacks }
    end
  end

  # GET /feedbacks/1
  # GET /feedbacks/1.json
  def show
    @feedback = Feedback.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @feedback }
    end
  end

  # GET /feedbacks/new
  # GET /feedbacks/new.json
  def new
    @feedback = Feedback.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @feedback }
    end
  end

  # GET /feedbacks/1/edit
  def edit
    @feedback = Feedback.find(params[:id])
  end

  # POST /feedbacks
  # POST /feedbacks.json
  def create
    @feedback = Feedback.new(params[:feedback])

    respond_to do |format|
      if @feedback.save
        format.html { redirect_to "index", notice: 'Feedback was successfully created.' }
        format.json { render json: @feedback, status: :created, location: @feedback }
      else
        format.html { render action: "new" }
        format.json { render json: @feedback.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /feedbacks/1
  # PUT /feedbacks/1.json
  def update
    @feedback = Feedback.find(params[:id])

    respond_to do |format|
      if @feedback.update_attributes(params[:feedback])
        format.html { redirect_to @feedback, notice: 'Feedback was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @feedback.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /feedbacks/1
  # DELETE /feedbacks/1.json
  def destroy
    @feedback = Feedback.find(params[:id])
    @feedback.destroy

    respond_to do |format|
      format.html { redirect_to feedbacks_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/feedbacks_helper.rb
module FeedbacksHelper
end

app/views/feedbacks/_form.html.erb
<%= form_for(@feedback) do |f| %>
  <% if @feedback.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@feedback.errors.count, "error") %> prohibited this feedback from being saved:</h2>

      <ul>
      <% @feedback.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email, 'Email:'%><br />
    <%= f.email_field :email %>
  </div>
  <div class="field">
    <%= f.label :content, 'Description of issue, suggestion, etc.:'%><br />
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit 'Send' %>
  </div>
<% end %>

app/views/feedbacks/new.html.erb
<h2>Give Us Your Feedback!</h2>
<p>Whether you have technical issues or suggestions fill out the form and let us know how we are doing.</t>

<%= render 'form' %>

<%= link_to 'Back', "../index" , id: "back_button", style: "color:#fff" %>

<script>
  $("#back_button").button();
</script>

app/views/feedbacks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Email:</b>
  <%= @feedback.email %>
</p>

<p>
  <b>Content:</b>
  <%= @feedback.content %>
</p>


<%= link_to 'Edit', edit_feedback_path(@feedback) %> |
<%= link_to 'Back', feedbacks_path %>